---
version: 2

references:
  restore_cache: &restore_cache
    - type: cache-restore
      name: Restore bundle cache
      key: customerio-ruby-{{ checksum "Gemfile.lock" }}

  save_cache: &save_cache
    - type: cache-save
      name: Store bundle cache
      key: customerio-ruby-{{ checksum "Gemfile.lock" }}
      paths:
        - vendor/bundle

jobs:
  ruby_27:
    working_directory: ~/customerio-ruby
    docker:
      - image: circleci/ruby:2.7.2
        environment:
          RAILS_ENV: test
    steps:
      - checkout
      - *restore_cache
      - run: bundle install
      - *save_cache
      - run: bundle exec rspec
  ruby_26:
    working_directory: ~/customerio-ruby
    docker:
      - image: circleci/ruby:2.6.6
        environment:
          RAILS_ENV: test
    steps:
      - checkout
      - *restore_cache
      - run: bundle install
      - *save_cache
      - run: bundle exec rspec
  ruby_25:
    working_directory: ~/customerio-ruby
    docker:
      - image: circleci/ruby:2.5.8
        environment:
          RAILS_ENV: test
    steps:
      - checkout
      - *restore_cache
      - run: bundle install
      - *save_cache
      - run: bundle exec rspec

workflows:
  test:
    jobs:
      - ruby_27
      - ruby_26
      - ruby_25
